### ISSUE TITLE
findRecord not working because primary key _id is outside data:{}

### ISSUE THREAD

**Issue by flynsequeira** [pouchdb-community/ember-pouch#180]
how do you findRecord in ember-pouch? Because the document schema is kind of like this {_id = "FGHJKL....",
data:{.....rest of the data.....};
}
So when you do findRecord('model-name',id_number).then()... it wont find the _id in the model-name object.

**Comment by broerse** [comment]
Like this: https://github.com/broerse/ember-cli-blog/blob/master/app/routes/post.js

**Comment by jiteshgupta1995** [comment]
I have same issue this works in routes but I was trying to make it work in controller but it doesn't show up. On debugging it doesn't go inside the .then(function(){}) break point.
I tried queryRecord but on .then(function(user)) , user was null don't know why?

**Comment by broerse** [comment]
It works on the route like this:

```javascript
import Ember from "ember";

export default Ember.Route.extend({
  model: function(params) {
    return this.store.findRecord('post', params.post_id).then(function(data) {
      console.log(data.get('id'));
      return data;
    });
  }
});
```

It should work the same way on the controller.

**Comment by flynsequeira** [comment]
params.post_id has the exact id correct? for me params is the id itself. eg. 'modelName_93839_94939'. 
function(params) {
    return this.store.findRecord('model-name', params).then(function(data) {
     //SomeDeleteCode
    });
  }
The model-name exists. And the particular id, which is the params here, exists. (Checked in pouch inspector) But I get an error saying it couldnt find the particular id in the model 'modelName' (and not 'model-name')

**Comment by flynsequeira** [comment]
@broerse But querying the data like this.store.queryRecord('model-name', {filter:{conditions of things that are inside the data:{} segment and not _id}}).then(function(data) {
//Try some code
});
This works. 
this.store.queryRecord('model-name', {filter:{_id:someIdNumberWhichActuallyExists}}).then(function(data) {
//Try some code
});
This doesn't work.

**Comment by broerse** [comment]
@flynsequeira I think `queryRecord` should not be used to find known id's. It see to be someting ember-data related. See:

> This method makes a request for one record, where the id is not known beforehand (if the id is known, use findRecord instead).

https://emberjs.com/api/data/classes/DS.Store.html#method_queryRecord

**Comment by flynsequeira** [comment]
But why isn't findRecord working? ... Refering to my above comment 
'''

params.post_id has the exact id correct? for me params is the id itself. eg. 'modelName_93839_94939'.
function(params) {
return this.store.findRecord('model-name', params).then(function(data) {
//SomeDeleteCode
});
}
The model-name exists. And the particular id, which is the params here, exists. (Checked in pouch inspector) But I get an error saying it couldnt find the particular id in the model 'modelName' (and not 'model-name')

'''

**Comment by broerse** [comment]
@flynsequeira I will push the branch I tested with so you can make the changes that don't work because I don't seem to exactly understand the problem.

**Comment by broerse** [comment]
Clone https://github.com/broerse/ember-cli-blog and checkout the `id` branch. Changes I made:

https://github.com/broerse/ember-cli-blog/blob/id/app/routes/post.js

**Comment by broerse** [comment]
@flynsequeira You can create a PR to the `id` branch so I can take a look.

**Comment by flynsequeira** [comment]
Hey sorry about the late response. Remove the branch because I don't exactly remember where it came up, but it's solved. I'll try and recreate the issue if I come across it again.
