### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by rimian** [pouchdb-community/ember-pouch#203]
In the paragraph titled "Query and QueryRecord"

This link returns a 404:

```https://github.com/pouchdb-community/pouchdb-find```

:)

**Comment by broerse** [comment]
@nolanlawson Where do we link to now?

**Comment by jlami** [comment]
I think this should become https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-find

**Comment by broerse** [comment]
@rimian @jlami Thanks! Changed in Beta.4
