### ISSUE TITLE
Trying ember quiz app

### ISSUE THREAD

**Issue by mehrajpasha** [pouchdb-community/ember-pouch#204]
I'm trying a quiz application using ember and pouch. For the starters, I'm just checking the answer given by user to the answer I saved in the db for only one question..I don't know how to interact my controller to db..I looked mango queries and wrote a query to fetch the record..Getting error that pouchdb-find can't be imported..Anyone help please ? submit(choice) is the method from hbs and controller file

`import Service from '@ember/service';
import PouchDB from 'pouchdb';
import PouchFind from 'pouchdb-find';
PouchDB.plugin(PouchFind);
PouchDB.debug.enable('pouchdb:find');

export default Service.extend({

		init() {
        this._super(...arguments);
        var host = this.get("http://localhost:5984/answers");
        let remoteDb = new PouchDB(host, { skipSetup: true });
        this.db = remoteDb;
    },

    submit(choice){
       return new Ember.RSVP.Promise((resolve, reject) => {
        this.db.find({
          selector: {_id:'b14ebb6203d037d313ff6be76b030edb'},
          fields: ['answer']
        }).then((response)=>{
                    if(response.docs.answer==choice){
                      response.send("The answer is correct");
                    }
        })
       })
    }
  
});`

**Comment by mehrajpasha** [comment]
Hi, I've a doubt we say import PouchDB from 'pouchdb'..from where are we importing this pouchdb ? package.json ? node_modules ?

**Comment by backspace** [comment]
Hey, it looks to me that you’re not using the Ember Data aspect Ember Pouch at all, so maybe you’re just looking for PouchDB help in general? Also, in your code, you don’t need to return an RSVP promise, you could just return the `find` promise directly.

**Comment by mehrajpasha** [comment]
see pouchdb methods are giving me error, when I try to update a document I need to put id too..since it is taking id again it gives me conflict..how do i update my documents ?

**Comment by broerse** [comment]
@mehrajpasha You only have to do this https://github.com/broerse/ember-cli-blog/blob/master/app/routes/posts.js#L33

Try cloning https://github.com/broerse/ember-cli-blog/ to how it works.
