### ISSUE TITLE
From AppCache to Service Workers

### ISSUE THREAD

**Issue by Voles** [pouchdb-community/ember-pouch#207]
At the moment [we're suggesting](https://github.com/pouchdb-community/ember-pouch#offline-first) users to use [broccoli-manifest](https://github.com/racido/broccoli-manifest) to setup an Offline First app using Ember Pouch.

But the application cache has been [removed from the Web standards](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache). I have been using [Ember Service Worker](http://ember-service-worker.com) instead and it seems to be the way to go for future-proof-offline-first-web-apps.

Would the team be interested if I'd update the Offline-First section using Ember Service Worker?

Btw, thanks for everyone's work on this extremely useful plugin 👏 🌻

**Comment by broerse** [comment]
@Voles Good point. We would like it very much if you work on the Offline-First section. Perhaps also mention https://github.com/broerse/ember-cli-blog/blob/master/ember-cli-build.js#L14

We are working hard to get v5.0.0 out of Beta so this is the right time to improve the readme.

**Comment by Voles** [comment]
@broerse I was a little too quick here. It looks like iOS 11.x does not yet support SW.

References:
- https://webkit.org/status/#specification-service-workers
- https://caniuse.com/#search=service

I don't think we should encourage users migrating to SW while support is not (yet) broadly covered. Let's keep an eye on the iOS 12 release to see if we can move this forward by then.

**Comment by blacktrident** [comment]
Hey I am new to Opensource having some experience about serviceworkers ,can I help?

**Comment by broerse** [comment]
@blacktrident Help is always welcome. I agree with @Voles that pushing people to SW while safari is not ready yet perhaps we should not encourage it in this module now.

@jkleinsc what do you think. Should we  encourage SW here now?

**Comment by jkleinsc** [comment]
I think SW should be encouraged.  Safari has service workers available in their technology preview (eg see https://webkit.org/blog/8060/release-notes-for-safari-technology-preview-47/).  We could still leave in the section about appcache with something like "if you need to support browsers that currently don't have service workers available, you can use Application Cache via broccoli-manifest as a fallback."

**Comment by broerse** [comment]
@Voles can you create something like @jkleinsc suggested?

**Comment by Voles** [comment]
@jkleinsc @broerse while it is indeed available in Safari TP, I expect it only to be available on iOS in September (when I expect them to release iOS 12).

What about I update that section and mention both scenarios? We could recommend AppCache for now but also mention SW and the fact that it currently does not yet work on Safari for iOS?

**Comment by broerse** [comment]
> What about I update that section and mention both scenarios?

I would like that.

**Comment by jkleinsc** [comment]
@Voles I don't have any more information about when it will land in iOS.  
I would recommend that when the document is updated, it should advocate to use service workers if available and use appcache as a fallback.  Service worker enabled browsers ignore appcache if a service worker is available so enabling both in your application is recommended if you are supporting a wide variety of browsers, particularly because the effort to implement both is fairly minimal.

**Comment by Voles** [comment]
I've updated the Offline First instructions based on what we discussed here. See #209.

@blacktrident @broerse @jkleinsc feedback is very much welcome!

**Comment by broerse** [comment]
@Voles Just merged this. Thanks! @blacktrident if you want to add or change something please make a new PR. We are always open for suggestions. If you need help with that, because you say you are new to Opensource, please let me know.

**Comment by Voles** [comment]
@broerse thanks for your quick action!
