### ISSUE TITLE
How to deal with conflicts

### ISSUE THREAD

**Issue by Voles** [pouchdb-community/ember-pouch#219]
I've been using Ember Pouch for a while. Now, there's some exceptions being thrown and I guess these occur because of syncing conflicts happening in Ember Pouch.

This is the output I see in the console:
<img width="1012" alt="screen shot 2018-03-09 at 20 29 07" src="https://user-images.githubusercontent.com/1725563/37225965-b27015aa-23d8-11e8-8291-b0ed3b78bba9.png">

The expanded error is quite verbose but doesn't really say anything valuable (as far as I can see).
<img width="774" alt="screen shot 2018-03-09 at 20 30 55" src="https://user-images.githubusercontent.com/1725563/37226005-d93e53ea-23d8-11e8-9b1d-cd86e44aa6d8.png">

I've been reading through the issues, documentation and code of PouchDB and found out there's a promise being rejected in the [`onChange` handler of the adapter](https://github.com/pouchdb-community/ember-pouch/blob/master/addon/adapters/pouch.js#L95).

My question: where in my Ember application should I deal with these conflicts? Should I extend the adapter? Catch the exception somewhere?

Any help would be very much appreciated. I'm happy to contribute to the documentation once I've figured out how to deal with conflicts properly.

Many thanks in advance! 🙏

**Comment by broerse** [comment]
@Voles Mailed you an example.
