### ISSUE TITLE
pouchdb iPhone issue

### ISSUE THREAD

**Issue by KevinK1507** [pouchdb-community/ember-pouch#223]
can you guys release a version with current pouchdb master branch ? This guys fix on master branch that iPhone problem on which user can't use pouchdb on iPhone Safari. In this moment we can just use it on iPhone Safari in private mode. See [here](https://github.com/pouchdb/pouchdb/issues/7057) and his fix on master branch: https://github.com/pouchdb/pouchdb/issues/6946

To reproduce and understand: check it on iPhone:
[before](https://attractive-brand.glitch.me) (doesn't work on iPhone, just on private mode)
[after fix]( https://awesome-resonance.glitch.me) (this is current master branch of pouchdb (which will work fine now)

fixed on current master branch of pouchdb. Please update to that. 

Thank you!

**Comment by broerse** [comment]
@KevinK1507 Will try today.

**Comment by broerse** [comment]
@KevinK1507 Will take a look this week.

**Comment by broerse** [comment]
@KevinK1507 Released v6.0.0 with failing tests because they are bugs in ember-data.

**Comment by broerse** [comment]
@KevinK1507 See why the tests fail here: https://github.com/emberjs/data/issues/5523

**Comment by broerse** [comment]
@KevinK1507 ember-data is fixed and all test pass again.
