### ISSUE TITLE
How to work on data already in couchdb?

### ISSUE THREAD

**Issue by pranavdubase** [pouchdb-community/ember-pouch#231]
I am new to ember-pouch, got stuck trying to understand the data store behavior. When i do  
`this.get('store').findAll('post')` it only return items which have `_id` starting with `post_2_......` to store. But the couchdb that is synced to contains about 1000 items. I would like to fetch all items on `this.get('store').findAll('post')`.

**Comment by broerse** [comment]
Not sure I understand the question. Perhaps take a look at https://github.com/broerse/ember-cli-blog/blob/master/app/adapters/application.js#L61

**Comment by jlami** [comment]
Ember-pouch uses https://github.com/pouchdb-community/relational-pouch which works with the `post_2_` prefix you mentioned. Other documents without those prefixes (or other prefixes that can be mapped to models in ember) are ignored.

**Comment by pranavdubase** [comment]
thank you. I got the idea how it's work.
