### ISSUE TITLE
How to add the pouchdb-find to ember-pouch as plugin

### ISSUE THREAD

**Issue by papakay** [pouchdb-community/ember-pouch#234]
Please how do i link pouchdb-find to ember-pouch

Inside adapters/application.js, i have something like this

```let db = new PouchDB(localDb);```

I've tried doing something like this db.plugin() but there is no method as plugin.

Please how do i get this to work? Thanks.

**Comment by backspace** [comment]
You’re meant to call `PouchDB.plugin`, not on the individual database (`db.plugin`).
