### ISSUE TITLE
Instructions for enabling debugging are wrong

### ISSUE THREAD

**Issue by jacobq** [pouchdb-community/ember-pouch#236]
The [README](https://github.com/pouchdb-community/ember-pouch#configuring-appadaptersapplicationjs) mentions being able to enable PouchDB debugging via `PouchDB.debug.enable('*');` but [as of v7.0.0 a plugin is needed instead](https://pouchdb.com/api.html#debug_mode). 

Instructions should probably be updated to note this.
See https://www.npmjs.com/package/pouchdb-debug

**Comment by broerse** [comment]
If you have time please make the PR

**Comment by jacobq** [comment]
Done -- hope you'll have a few minutes to look at the tougher problem(s) in #235 / #237 soon :)

**Comment by jacobq** [comment]
I rebased this in case you still want it. Is this project still being (actively) maintained?

**Comment by backspace** [comment]
It’s barely maintained, as you can see. I’ll be coming back to it eventually when I’m working on a new application, but I think people who’ve done work on it are mostly just using what already exists vs fixing bugs and adding features. Thanks for the PR, though!
