### ISSUE TITLE
ember-data canary test appear broken

### ISSUE THREAD

**Issue by jacobq** [pouchdb-community/ember-pouch#248]
This line doesn't appear to be working like it's supposed to:
https://github.com/pouchdb-community/ember-pouch/blob/294b132239b0ace6351e27057ca57ec7fdfb39eb/config/ember-try.js#L110

e.g. 
https://travis-ci.org/pouchdb-community/ember-pouch/jobs/610602635

**Comment by jlami** [comment]
Fixed by #254
