### ISSUE TITLE
Working with _users

### ISSUE THREAD

**Issue by Voles** [pouchdb-community/ember-pouch#253]
Hi all,

I'm working on an app which has a database with application models. Now I'm trying to implement authentication, which seems to be done using the `_users` database.

Can I have ember-pouch deal with two databases in the same application? Eg. I would like to fetch the users from the `_users` database. And the application data from another database (eg. `my-app`.

Thanks!

**Comment by backspace** [comment]
I believe you can accomplish this by having a separate adapter for users, with its own PouchDB configuration. I feel like I‘ve done this before but sadly can’t find an example of it.

**Comment by Voles** [comment]
@backspace thanks for your reply!

I see there's a `changeDb` on the Ember Pouch adapter. But I actually want to work with both databases at the same time.

**Comment by backspace** [comment]
I mean that you could have `app/adapters/user.js` with its own `db` attribute that differs from the application adapter, then `user` models will work with that database instead.

**Comment by broerse** [comment]
@Voles Maybe try https://github.com/martinic/ember-simple-auth-pouch

**Comment by Voles** [comment]
@backspace @broerse thanks, I'll go for Ember Simple Auth Pouch :-)
